[tools]
biome = "2.3"
node = "25"
powershell = "7"

[tasks.it]
description = "Run the thing"
run = "node ./index.mjs"

[tasks.fmt]
description = "Format all files"
shell = "pwsh -c"
run = "biome format --fix --indent-style=space --indent-width=4 (get-item *.mjs) (get-item */*.mjs)"
