[tools]
biome = "2.3"
node = "25"

[tasks.setup]
description = "Setup dependencies"
run = "npm ci"

[tasks.it]
description = "Run the thing"
run = "node ./index.mjs"

[tasks.fmt]
description = "Format all files"
run = "biome format --fix"
